# Custom Redis Dockerfile (for show/demo purposes)
FROM redis:latest

LABEL maintainer="https://github.com/prateushsharma/ZaZa"

# Custom loglevel or config can go here
CMD ["redis-server", "--loglevel", "notice"]
